# Generated by Django 5.1 on 2024-08-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cartItem',
            new_name='cart',
        ),
    ]
